---
# normally collectd is already installed
- name: Collectd | install packages
  apt: pkg={{item}} state=installed
  with_items:
    - collectd
  tags: 
    - collectd

- name: Collectd | Open {{collectd_port}} on lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{collectd_port}}
  tags: 
    - collectd
    - ufw


