---
# normally collectd is already present
- name: Collectd | install packages
  apt: pkg={{item}} state=present
  with_items:
    - collectd
  tags: 
    - collectd

- name: Collectd | Open {{collectd_port}} on lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{collectd_port}}
  tags: 
    - collectd
    - ufw

- name: Collectd | Deploy monit config
  template: src=monit.d/collectd-server.conf.j2  dest=/etc/monit/conf.d/collectd-server.conf
  notify:
    - reload monit
  tags:
    - collectd
    - monit


