---
# normally collectd is already installed
- name: install collectd
  apt: pkg={{item}} state=installed
  with_items:
  - collectd
  tags: collectd

- name: Set firewall rules for collectd server
  command: "ufw allow from 192.168.0.0/24 to any port 25826"
  tags: collectd

- name: Install ruby
  apt: name={{item}} state=present
  with_items:
   - librrd-ruby
   - ruby
   - ruby-dev
  tags: visage-app

- name: Install gem visage
  gem: name={{item}} state=present
  with_items:
   - sinatra
   - optiflag
   - rack
   - tilt
   - visage-app
  tags: visage-app

- name: Open port 9292 on firewall for visage
  command: "ufw allow from 192.168.0.0/24 to any port 9292"
  tags: visage-app

- name: Start visage
  command: "visage-app start&"
  tags: visage-app
