---
# normally collectd is already installed
- name: Collectd | install packages
  apt: pkg={{item}} state=installed
  with_items:
  - collectd
  tags: collectd

- name: Collectd | Set firewall rules 
  ufw: rule=allow src=192.168.0.0/24 dest=any port=25826
  tags: collectd

- name: Collectd | Install ruby package
  apt: name={{item}} state=present
  with_items:
   - librrd-ruby
   - ruby
   - ruby-dev
  tags: visage-app

- name: Visage | Install gem visage
  gem: name={{item}} state=present
  with_items:
   - sinatra
   - optiflag
   - rack
   - tilt
   - visage-app
  tags: visage-app

- name: Visage | Open port 9292 on firewall for visage
  ufw: rule=allow src=192.168.0.0/24 dest=any port=9292
  tags: visage-app

- name: Vidage | Start server
  command: "visage-app start&"
  tags: visage-app
