# from https://github.com/johnhamelink/ansible-elasticsearch
---
- name: Elasticsearch | ensure 1.0.x repository is installed
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main" state=present update_cache=yes
  when: "ansible_lsb['codename'] == 'precise'"
  tags: elasticsearch

- name: Elasticsearch | install package
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre
    - elasticsearch
  tags: 
    - elasticsearch

- name: Elasticsearch | Create data(s) dir(s)
  file: dest=/media/{{item}}/var/data/elasticsearch
        state=directory
        owner={{deploy_user}} 
        group={{deploy_user}} 
        mode=0711
  with_items:
    - data1
    - data2
  tags:
    - elasticsearch


- name: Elasticsearch | Set firewall rules open port {{es_port}}
  ufw: rule=allow src={{fw_subnet}} dest=any port={{es_port}}
  tags: 
    - elasticsearch

- name: Elasticsearch | Set firewall rules open port {{es_transport_port}}
  ufw: rule=allow src={{fw_subnet}} dest=any port={{es_transport_port}}
  tags:  
    - elasticsearch

- name: Elasticsearch | Configure push from rsyslog
  template: src=rsyslog.d/{{item}}.j2 dest=/etc/rsyslog.d/{{item}}
  with_items:
    - 98-elasticsearch.conf
  tags: 
    - elasticsearch
    - rsyslog
  notify: 
    - restart rsyslog

- name: Elasticsearch | install config is in place
  template: src=elasticsearch.conf.j2 dest=/etc/elasticsearch/elasticsearch.conf
  notify:
    - restart elasticsearch
  tags: 
    - elasticsearch
