# from https://github.com/johnhamelink/ansible-elasticsearch
---
- name: Ensure Elasticsearch 1.0.x repository is installed
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main" state=present update_cache=yes
  tags: elasticsearch

- name: Ensure elasticsearch is installed
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre
    - elasticsearch
  tags: elasticsearch

- name: Ensure elasticsearch config is in place
  template: src=elasticsearch.conf.j2 dest=/etc/elasticsearch/elasticsearch.conf
  notify:
    - restart elasticsearch
  tags: elasticsearch
