---
- name: Grafana | download package
  get_url: url=http://grafanarel.s3.amazonaws.com/grafana-{{grafana_version}}.tar.gz
           dest=/home/{{deploy_user}}/src
           owner={{deploy_user}}
           group={{deploy_user}}
           mode=0644
  tags: 
    - grafana

- name: Grafana | unpack
  shell: "cd /var/www && test ! -d grafana-{{grafana_version}} && tar zxvf /home/{{deploy_user}}/src/grafana-{{grafana_version}}.tar.gz || true"
  tags: 
    - grafana


- name: Grafana | install config is in place
  template: src=grafana.conf.j2 
            dest=/var/www/grafana-{{grafana_version}}/config.js
            mode=0644
  tags: 
    - grafana


