---
- name: Graphite | install packages
  apt: name={{item}} state=latest
  with_items:
   - python-rrdtool
   - python-whisper
   - graphite-carbon
   - graphite-web
  tags: graphite

- name: Graphite | activate graphite in collectd
  lineinfile: dest=/etc/collectd/collectd.conf
              state=present
              regexp="^#LoadPlugin write_graphite"
              line="LoadPlugin write_graphite"
  tags: 
   - graphite
   - collectd
  notify:
    - restart collectd

