---
- name: Influxdb | create user influxdb if needed
  user: name=influxdb generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  tags: influxdb
  
- name: Influxdb | check ~/tmp exist
  file: path=/home/{{deploy_user}}/tmp
        state=directory
        owner={{deploy_user}}
        group={{deploy_user}}
        mode=0755
  tags: influxdb
  
- name: Influxdb | download package
  get_url: url=http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
           dest=/home/{{deploy_user}}/tmp/influxdb_latest_amd64.deb
           mode=0644
  tags: influxdb

- name: Influxdb | install package
  apt: deb=/home/{{deploy_user}}/tmp/influxdb_latest_amd64.deb
  tags: influxdb

- name: Influxdb | Check permission
  file: path={{item}}
        state=touch
        owner=influxdb
        group=influxdb
        mode=0644
  with_items:
     - /var/log/influxdb.log 
  tags: influxdb

- name: Influxdb | Check permission
  file: path={{item}}
        state=file
        owner=influxdb
        group=influxdb
        mode=0755
  with_items:
    - /opt/influxdb/current/scripts/init.sh
    - /opt/influxdb/current/influxdb
  tags: influxdb

- name: Influxdb | Configure collectd plugin
  template: src=collectd/collectd.conf.d/influxdb.conf.j2 
            dest=/etc/collectd/collectd.conf.d/influxdb.conf
  tags: 
    - collectd
    - influxdb
  notify: 
    - restart collectd

- name: Influxdb | Copy configuration (to non standar place)
  template: src=influxdb.toml.j2 
            dest=/opt/influxdb/shared/config.toml
            mode=0644
            owner=influxdb
            group=influxdb
  tags: 
    - influxdb
  notify: 
    - restart influxdb

- name: Influxdb | activate graphite in collectd
  lineinfile: dest=/etc/collectd/collectd.conf
              state=present
              regexp="^#LoadPlugin write_graphite"
              line="LoadPlugin write_graphite"
  tags: 
   - influxdb
   - collectd
  notify:
    - restart collectd

- name: Influxdb | Open admin port 8083 on local lan
  ufw: rule=allow src={{fw_subnet}} dest=any port=8083
  tags: influxdb

- name: Influxdb | Open api port {{influxdb_port_api}} on local lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{influxdb_port_api}}
  tags: influxdb

- name: Influxdb | Open graphite compatible api on tcp port {{carbon_port}} on local lan
  ufw: rule=allow src={{fw_subnet}} dest=any proto=tcp port={{carbon_port}}
  tags: influxdb

- name: Influxdb | Open graphite compatible api on udp port {{carbon_port}} on local lan
  ufw: rule=allow src={{fw_subnet}} dest=any proto=udp port={{carbon_port}}
  tags: influxdb

- name: Influxdb | Close raft port 8090 outside of local lan
  ufw: rule=allow src={{fw_subnet}} dest=any proto=udp port=8090
  tags: influxdb

#- name: Influxdb | Open replication port if needed with slaves
#  ufw: rule=allow src={item} dest=any proto=udp port=8099
#  with_items:
#    - 192.168.0.17
#    - 192.168.0.19
#  tags: influxdb

- name: Influxdb | Deploy monit config
  template: src=monit.d/influxdb.conf.j2  dest=/etc/monit/conf.d/influxdb.conf
  notify:
    - reload monit
  tags:
    - influxdb
    - monit



