# from https://github.com/johnhamelink/ansible-logstash
---
- name: Ensure Logstash 1.3.x repository is present
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main" update_cache=yes
  when: "ansible_lsb['codename'] == 'precise'"
  tags: logstash

- name: Ensure logstash is present
  apt: pkg={{item}} state=present
  with_items:
    - openjdk-7-jre
    - logstash
  tags: logstash

- name: Ensure logstash service config is in place
  copy: src=logstash_default dest=/etc/default/logstash
  notify:
    - restart logstash
  tags: logstash

- name: Ensure logstash config is in place
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf mode=0644 owner=logstash group=logstash
  notify:
    - restart logstash
  tags: logstash

- name: Ensure SSL certificates have the correct directories
  file: path=/etc/pki/tls/{{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - certs
    - private
  notify:
    - restart logstash
  tags: logstash

- name: Ensure logstash-forwarder has its SSL certificate
  copy: src=logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwarder.crt owner=root group=root mode=0500
  notify:
    - restart logstash
  tags: logstash

- name: Ensure logstash-forwarder has its SSL private key
  copy: src=logstash-forwarder.key dest=/etc/pki/tls/private/logstash-forwarder.key owner=root group=root mode=0700
  notify:
    - restart logstash
  tags: logstash

- name: Ensure logstash boots on startup
  shell: update-rc.d logstash defaults
  notify:
    - restart logstash  
  tags: logstash

- name: Open port 5544 on firewall for rsyslog logs
  ufw: rule=allow src={{fw_subnet}} dest=any port=5544
  tags: 
    - logstash
    - ufw

