---
- name: Rsyslog | Install elasticsearch plugin
  apt: name={{item}} state=present
  with_items:
   - rsyslog-elasticsearch
  when: 
    - "ansible_lsb['codename'] == 'trusty'"
  tags:
    - rsyslog

- name: Rsyslog | Create index exist in elasticseach
  shell: "curl -XPOST http://localhost:{{es_port}}/logstash-ind"
  tags:
    - rsyslog

- name: Rsyslog | Change conf to open syslog reception
  lineinfile: dest=/etc/rsyslog.conf
              regexp='^#\$ModLoad imudp.*$'
              state=present     
              line='$ModLoad imudp'
  tags:
    - rsyslog

- name: Rsyslog | Change conf to open syslog reception
  lineinfile: dest=/etc/rsyslog.conf
              regexp='^#\$UDPServerRun 514.*$'
              state=present     
              line='$UDPServerRun {{rsyslog_port}}'
  tags:
    - rsyslog

- name: Rsyslog | Change conf to open syslog reception
  lineinfile: dest=/etc/rsyslog.conf
              regexp='^#\$ModLoad imtcp.*$'
              state=present     
              line='$ModLoad imtcp'
  tags:
    - rsyslog

- name: Rsyslog | Change conf to open syslog reception
  lineinfile: dest=/etc/rsyslog.conf
              regexp='^#\$InputTCPServerRun 514.*$'
              state=present     
              line='$InputTCPServerRun {{rsyslog_port}}'
  tags:
    - rsyslog

- name: Rsyslog | Open port {{rsyslog_port}} on lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{rsyslog_port}}
  tags: 
    - rsyslog
    - ufw

