---
- name: Collectd | Install ruby package
  apt: name={{item}} state=present
  with_items:
   - librrd-ruby
   - ruby
   - ruby-dev
  tags: visage-app

- name: Visage | Install bundler
  apt: pkg=bundler state=present
  with_items:
    - bundler
    - phantomjs
  tags: visage

- name: Visage | check ~/src exist
  file: path=/home/{{deploy_user}}/src/visage
        state=directory
        owner={{deploy_user}}
        group={{deploy_user}}
        mode=0755
  tags: visage
  
- name: Visage | Checkout software
  git: repo=https://github.com/auxesis/visage.git
       dest=/home/{{deploy_user}}/src/visage
       version=master
  when: 
    - maintenance is defined
  tags: 
    - do-upgrade
    - visage

- name: Visage | Create conf dir
  file: dest=/etc/visage 
        state=directory
        owner={{deploy_user}} 
        group={{deploy_user}} 
        mode=0711
  tags: visage

- name: Visage | Bundled
  shell: "cd /home/{{deploy_user}}/src/visage && /usr/bin/bundle install"
  tags: visage

- name: Visage | Copy procfile
  template: src=visage.conf.j2 
            dest=/etc/visage/Procfile
            owner={{deploy_user}} 
            group={{deploy_user}} 
            mode=0600
  tags: visage

- name: Visage | Copy supervisor config
  template: src=supervisor/visage.conf.j2 
            dest=/etc/supervisor/conf.d/visage.conf
            owner=root
            group=root
            mode=0600
  tags: 
    - visage
    - supervisor
  notify:
    - restart supervisor

- name: Visage | Open port {{visage_port}} on lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{visage_port}}
  tags: 
    - visage
    - ufw

- name: Visage | Deploy monit config
  template: src=monit.d/visage.conf.j2  dest=/etc/monit/conf.d/visage.conf
  notify:
    - reload monit
  tags:
    - visage
    - monit

