---
# ======================================================================
# apply to the only host
# ======================================================================
- hosts: all
  remote_user: pierre
  become_user: root
  become: true

  roles:
    - common
    - hardware
    
  post_tasks:
  - name: Notify slask
    slack:
       domain: "{{slack_domain}}"
       token: "{{slack_token}}"
       msg: "{{inventory_hostname}}/{{ansible_default_ipv4.address}} completed"

              
