---
# ======================================================================
# apply to the only host
# ======================================================================
- hosts: all
  remote_user: pierre
  sudo_user: root
  sudo: True

  roles:
  - common
  - databases
  - admin
  - tsuru
