---
# ======================================================================
# apply to the only host
# ======================================================================
- hosts: all
  remote_user: pierre
  sudo_user: root
  sudo: True

  roles:
    - common
    - hardware
    - databases
    - webservers
    - admin
    - tsuru
    - 7pi
    - X11
    - development
