---
- name: Gandalf | install package
  apt: name={{item}} state=installed
  with_items:
   - curl
   - gandalf-server
  tags: gandalf

- name: Gandalf | Create bare-temaplte directory
  file: path=/home/git/bare-template/hooks state=directory mode=0755 owner=git group=git
  tags: gandalf

- name: Gandalf | update post receive
  command: "sudo curl https://raw.githubusercontent.com/gandalf/gandalf/master/misc/git-hooks/post-receive -o /home/git/bare-template/hooks/post-receive"
  tags: gandalf

- name: Gandalf | set execution bit for conf
  file: path=/home/git/bare-template/hooks/post-receive mode=0755 owner=git group=git
  tags: gandalf

- name: Gandalf | set owner for conf
  command: chown -R git:git /home/git/bare-template
  tags: gandalf

- name: Gandalf | deploy configuration file
  template: src=gandalf.conf.j2 dest=/etc/gandalf.conf
  tags: gandalf 

- name: Gandalf | Start the service
  service: name=gandalf-server state=started enabled=true
  tags: gandalf

- name: Gandalf | Open port 8000
  ufw: rule=allow port=8000 proto=tcp src=192.168.0.0/24 state=reloaded
  tags: gandalf

- name: Gandalf | Start the associated git service 
  service: name=git-daemon state=started enabled=true
  tags: gandalf
