---
- name: Hipache | install nodejs
  apt: name={{item}} state=installed
  with_items:
   - nodejs
  tags: hipache

- name: Hipache | install hipache
  command: "npm install hipache -g"
  tags: hipache

- name: Hipache | create directory for log
  command: mkdir -p /var/log/hipache
  tags: hipache

- name: Hipache | create directory for etc files
  command: mkdir -p /etc/hipache
  tags: hipache

- name: Hipache | install config file
  template: src=hipache.conf.j2 dest=/etc/hipache/hipache.conf
  tags: hipache

- name: Hipache | install init file
  template: src=hipache.init.j2 dest=/etc/supervisor/conf.d/hipache.conf
  tags: hipache

- name: Hipache | copy SSL certificate
  copy: src=hipache.crt dest=/etc/pki/tls/certs/hipache.crt owner=root group=root mode=0500
  tags: hipache

- name: Hipache | copy private key
  copy: src=hipache.key dest=/etc/pki/tls/private/hipache.key owner=root group=root mode=0500
  tags: hipache

- name: Hipache | Open port 10080
  ufw: rule=allow port=10080 proto=tcp src=192.168.0.0/24 state=reloaded
  tags: hipache

- name: Hipache | Open port 10443
  ufw: rule=allow port=10443 proto=tcp src=192.168.0.0/24 state=reloaded
  tags: hipache

- name: Hipache | Start the service via supervisor
  supervisorctl: name=hipache state=restarted
  tags: hipache


