---
- name: Tsuru | Get last platform-setup 
  get_url: url=https://raw.githubusercontent.com/tsuru/tsuru/master/misc/platforms-setup.js dest=/tmp/platforms-setup.js mode=0444     
  tags: tsuru

- name: Tsuru | Create user tsuru in mongodb
  mongodb_user: database=tsuru name=tsuru password=tsuru state=present
  tags: tsuru

- name: Tsuru | import platform-setup.js into mongod
  shell: "cat /tmp/platforms-setup.js | /usr/bin/mongo tsuru"
  tags: tsuru



