---
- name: Tsuru | add mongodb
  apt: name={{item}} state=installed
  with_items:
   - mongodb
   - python-pymongo
  tags: tsuru

- name: Tsuru | Get last platform-setup 
  get_url: url=https://raw.githubusercontent.com/tsuru/tsuru/master/misc/platforms-setup.js dest=/tmp/platforms-setup.js mode=0440     
  tags: tsuru

- name: Tsuru | Create user tsuru in mongodb
  mongodb_user: database=tsuru name=tsuru password=tsuru state=present
  tags: tsuru

- name: Tsuru | import platform-setup.js into mongod
  command: cat /tmp/platforms-setup.js | mongo tsuru
  tags: tsuru

- name: Mongodb | Start the service
  service: name=mongodb state=started enabled=true
  tags: mongodb



