---
- name: Tsuru | install package
  apt: name={{item}} state=installed
  with_items:
   - tsuru-server
  tags: tsuru

- name: Tsuru | check required directory
  file: path=/home/application/current owner=tsuru group=tsuru mode=0755 state=directory
  tags: tsuru

- name: Tsuru | edit default
  replace: dest=/etc/default/tsuru-server regexp="=no$" replace="=yes" backup=yes
  tags: tsuru

- name: Tsuru | copy SSL certificate
  copy: src=tsuru.crt dest=/etc/pki/tls/certs/tsuru.crt owner=root group=root mode=0500
  tags: tsuru

- name: Tsuru | copy private key
  copy: src=tsuru.key dest=/etc/pki/tls/private/tsuru.key owner=root group=root mode=0500
  tags: tsuru

- name: Tsuru | deploy configuration file
  template: src=tsuru.conf.j2 dest=/etc/tsuru.conf
  notify:
    - restart tsuru-ssh-agent
    - restart tsuru-server-api
    - restart tsuru-server-collector
  tags: tsuru 

- name: Tsuru | Open port {{gandalf_port}}
  ufw: rule=allow port={{gandalf_port}} proto=tcp src={{fw_subnet}} state=reloaded
  tags: tsuru

- name: Tsuru | Open port {{tsuru_port}}
  ufw: rule=allow port={{tsuru_port}} proto=tcp src={{fw_subnet}} state=reloaded
  tags: tsuru

- name: Tsuru | Open port {{tsuru_ssh_port}} for ssh
  ufw: rule=allow port={{tsuru_ssh_port}} proto=tcp src={{fw_subnet}} state=reloaded
  tags: tsuru

- name: Tsuru | Start ssh service
  service: name=tsuru-ssh-agent state=started enabled=true
  tags: tsuru

- name: Tsuru | Start server api service
  service: name=tsuru-server-api state=started enabled=true
  tags: tsuru

- name: Tsuru | Start server collector service
  service: name=tsuru-server-collector state=started enabled=true
  tags: tsuru





  









