---
- name: Xorg | Ensure ppa is present
  apt_repository: repo='ppa:xorg-edgers/ppa'
  tags: Xorg

- name: Xorg | add other packages
  apt: name="{{item}}" state=present
  with_items:
   - nvidia-384
   - vdpau-va-driver
   - vainfo
  tags: Xorg





