---
- name: Mesos | add apt key for mesosphere
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF
  tags:
    - apt

- name: Mesos | add repo for apt
  apt_repository: repo='deb http://repos.mesosphere.io/ubuntu trusty main' state=present
  tags:
    - apt
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "trusty"

- name: Mesos | Install packages for Ubuntu/Trusty
  apt: pkg={{item}}
  with_items:
    - certifi
    - mesos.cli
  tags:
    - python
    - mesos
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "trusty"

- name: Mesos | Install packages
  apt: pkg={{item}}
  with_items:
    - python-kazoo
    - zookeeper
  tags:
    - python
    - mesos
    
