---
- name: aubergine | Copy source
  git: repo=https://bitbucket.org/pierreaubert/aubergine.git
       dest=/home/{{deploy_user}}/src/7pi/aubergine
       version=master
  tags: 7pi

- name: aubergine | Check permission
  command: chown -R {{deploy_user}}:{{deploy_user}} /home/{{deploy_user}}/src/7pi/aubergine 


