---
- name: crawler | Copy source
  git: repo=https://bitbucket.org/pierreaubert/crawler.git
       dest=/home/{{deploy_user}}/src/7pi/crawler
       version=develop
  tags: 
    - 7pi
    - crawler

- name: crawler | Copy config file
  template: src=7pi-crawler.conf.j2 dest=/etc/7pi/7pi-crawler.conf backup=yes owner={{deploy_user}} mode=0600
  tags: 
    - 7pi
    - crawler


#- name: crawler | Copy config file for supervisord
#  template: src=supervisor/7pi-crawler.conf.j2 dest=/etc/supervisor/conf.d/7pi-crawler.conf
#  tags: 7pi

#- name: crawler | Restart via supervisord conf
##  supervisorctl: name=crawler state=restarted
#  command: service supervisor restart
#  tags: 7pi
