---
- name: postgresql | create users
  shell: "sudo -u postgres createuser -U {{deploy_user}} -S -R -D -e {{item}} || true"
  with_items:
    - sso
    - rssfeeds
    - userfeeds
  tags: 7pi

- name: postgresql | create db 
  shell: "sudo -u postgres createdb -O {{item}} {{item}} || true"
  with_items:
    - sso
    - rssfeeds
    - userfeeds
  tags: 7pi

- name: postgresql | set password for sso
  command: sudo -u postgres psql {{ spi_sso_pg_username }} -c "ALTER USER {{spi_sso_pg_username}} with password '{{ spi_sso_pg_password }}';"
  tags: 7pi

- name: postgresql | give network access to sso
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='.*sso.*'  
              state=present
              line='host         sso             sso          127.0.0.1/32            md5'
  tags: 7pi

- name: postgresql | set password for rssfeeds
  command: sudo -u postgres psql {{ spi_rssfeeds_pg_username }} -c "ALTER USER {{spi_rssfeeds_pg_username}} with password '{{ spi_rssfeeds_pg_password }}';"
  tags: 7pi


- name: postgresql | grant all on table rssfeeds to {{spi_rssfeeds_pg_username}}
  command: sudo -u postgres psql {{deploy_user}} -d rssfeeds -c 'GRANT ALL ON TABLE {{item}} TO {{spi_rssfeeds_pg_username}};'
  with_items:
    - rssfeeds
    - rssitems
    - stats
    - httpredirects
  tags: 7pi

- name: postgresql | grant all on table rssfeeds to {{spi_rssfeeds_pg_username}}
  command: sudo -u postgres psql {{deploy_user}} -d rssfeeds -c 'GRANT ALL ON SEQUENCE {{item}}_seq TO {{spi_rssfeeds_pg_username}};'
  with_items:
    - rssfeeds
    - rssitems
  tags: 7pi

- name: postgresql | give network access to rssfeeds
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='.*rssfeeds.*'  
              state=present
              line='host         rssfeeds             rssfeeds          127.0.0.1/32            md5'
  tags: 7pi

- name: postgresql | set password for userfeeds
  command: sudo -u postgres psql {{ spi_userfeeds_pg_username }} -c "ALTER USER {{spi_userfeeds_pg_username}} with password '{{ spi_userfeeds_pg_password }}';"
  tags: 7pi

- name: postgresql | give network access to userfeeds
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='.*userfeeds.*'  
              state=present
              line='host         userfeeds             userfeeds          127.0.0.1/32            md5'
  tags: 7pi

