---
- name: rssfeeds | Copy source
  git: repo=https://bitbucket.org/pierreaubert/rssfeeds.git
       dest=/home/{{deploy_user}}/src/7pi/rssfeeds
       version=develop
  tags: 
    - 7pi
    - rssfeeds

- name: rssfeeds | Check permission
  command: chown -R {{deploy_user}}:{{deploy_user}} /home/{{deploy_user}}/src/7pi/rssfeeds 
  tags: 
    - 7pi
    - rssfeeds

- name: rssfeeds | Copy config file
  template: src=7pi-rssfeeds.conf.j2 dest=/etc/7pi/7pi-rssfeeds.conf backup=yes owner={{deploy_user}} mode=0600
  tags: 
    - 7pi
    - rssfeeds

- name: rssfeeds | Copy config file for supervisord
  template: src=supervisor/7pi-rssfeeds.conf.j2 dest=/etc/supervisor/conf.d/7pi-rssfeeds.conf
  tags: 
    - 7pi
    - rssfeeds

- name: rssfeeds | Restart via supervisord conf
  supervisorctl: name=rssfeeds state=restarted
  tags: 
    - 7pi
    - rssfeeds

- name: rssfeeds | Copy config file for rsyslog
  template: src=rsyslog.d/7pi-rssfeeds.conf.j2 dest=/etc/rsyslog.d/30-7pi-rssfeeds.conf
  notify:
    - restart rsyslog
  tags: 
    - 7pi
    - rssfeeds
    - rsyslog

- name: rssfeeds | Restart via rsyslogd conf
  service: name=rsyslog state=restarted
  tags: 
    - 7pi
    - rssfeeds
    - rsyslog
