---
- name: sso | Copy source
  git: repo=https://bitbucket.org/pierreaubert/sso.git
       dest=/home/{{deploy_user}}/src/7pi/sso
       version=release/1.3
  tags: 
    - 7pi
    - sso

- name: sso | Check permission
  command: chown -R {{deploy_user}}:{{deploy_user}} /home/{{deploy_user}}/src/7pi/sso 
  tags: 
    - 7pi
    - sso

- name: sso | Copy config file
  template: src=7pi-sso.conf.j2 dest=/etc/7pi/7pi-sso.conf backup=yes owner={{deploy_user}} mode=0600
  tags: 
    - 7pi
    - sso

- name: sso | Copy config file for supervisord
  template: src=supervisor/7pi-sso.conf.j2 dest=/etc/supervisor/conf.d/7pi-sso.conf
  notify:
    - restart supervisord
  tags: 
    - 7pi
    - sso
    - supervisor

- name: sso | Restart via supervisord conf
  supervisorctl: name=sso state=restarted
  tags: 
    - 7pi
    - sso
    - supervisor

- name: sso | Copy config file for rsyslog
  template: src=rsyslog.d/7pi-sso.conf.j2 dest=/etc/rsyslog.d/30-7pi-sso.conf
  notify:
    - restart rsyslog
  tags: 
    - 7pi
    - sso
    - rsyslog

- name: sso | Restart via rsyslogd conf
  service: name=rsyslog state=restarted
  tags: 
    - 7pi
    - sso
    - rsyslog
