---
- name: gunicorn | Install packages
  apt: pkg={{item}}
  with_items:
    - gunicorn
  tags: 
    - gunicorn

- name: gunicorn | Disable gunicorn service
  service: name=gunicorn state=stopped enable=false
  tags: 
    - gunicorn
  

