---
- name: gunicorn | Install packages
  apt: pkg={{item}}
  with_items:
    - gunicorn
  tags: gunicorn

- name: gunicorn | Disable gunicorn service
  command: service gunicorn stop
  tags: gunicorn
  

