---
- name: Install nginx and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - nginx-naxsi
  tags: 
    - nginx
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "trusty"

- name: Install nginx and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - nginx-full
  tags: 
    - nginx
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "vivid"

- name: Remove APache2
  apt: pkg={{ item }} state=removed
  with_items:
    - apache2

- name: Expose nginx on internet on port 80
  ufw: rule=allow proto=tcp port=80  
  tags: 
    - nginx
    - ufw

- name: Expose nginx on internet on port 443
  ufw: rule=allow proto=tcp port=443
  tags: 
    - nginx
    - ufw

- name: copy nginx config files
  template: src=nginx/{{item}}.j2 
            dest=/etc/nginx/{{item}}
  with_items:
    - nginx.conf
    - naxsi.rules
    - naxsi_core.rules
  notify: 
    - restart monit
  tags: 
    - nginx

- name: Nginx | Deploy monit config
  template: src=monit.d/nginx.conf.j2  dest=/etc/monit/conf.d/nginx.conf
  notify: 
    - reload monit
  tags:
    - nginx
    - monit

