---
# Handlers for common notifications

- name: restart ntp
  service: name=ntp state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart supervisor
  service: name=supervisor state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: restart collectd
  service: name=collectd state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart sysctl
  command: sysctl -p

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

