---
- name: Synergy | install
  apt: pkg={{item}} state=installed
  with_items:
  - synergy
  tags: synergy

- name: Synergy | add config file
  acl: name=/home/{{deploy_user}}/.xprofile 
       entity={{deploy_user}} 
       etype=user
       permissions=rw
       state=present 
  tags: synergy

- name: Synergy | insert config
  lineinfile: dest=/home/{{deploy_user}}/.xprofile 
              line="synergyc --daemon {{synergy_server}}"
  tags: synergy

