---
user: pierre
fw_subnet: 192.168.1.0/24
# --------------------------------------------------------------------
# collectd
# --------------------------------------------------------------------
collectd_host: 192.168.1.18
collectd_port: 25826
# ----------------------------------------------------------------------
# Rsyslog
# ----------------------------------------------------------------------
rsyslog_host: 192.168.1.18
rsyslog_port: 5544
# --------------------------------------------------------------------
# which host for es
# --------------------------------------------------------------------
es_host: 192.168.1.18
es_port: 9200
es_transport_port: 9300
es_bind_host: 192.168.1.18
es_publish_host: 192.168.1.18
# elasticsearch domain exposed by nginx and not on localhost:9200
es_address: http://192.168.1.18:7080/es
# --------------------------------------------------------------------
# logstash
# --------------------------------------------------------------------
logstash_domain: 192.168.1.18:5043
# --------------------------------------------------------------------
# kibana config
# --------------------------------------------------------------------
kibana_url: https://github.com/elasticsearch/kibana/archive/master.zip
kibana_user: kibana
kibana_domain: 192.168.1.18
kibana_pwd: banana2013
kibana_domain: 192.168.1.18
kibana_port: 7080
# --------------------------------------------------------------------
# backup all by default
# --------------------------------------------------------------------
backup_main_dir: /
# where to backup
backup_repository: /media/backup/ubuntu
# --------------------------------------------------------------------
# carbon / influxdb
# --------------------------------------------------------------------
carbon_host: 192.168.1.18
carbon_relay_port: 5553
carbon_port: 2003
# --------------------------------------------------------------------
# influxdb 
# --------------------------------------------------------------------
influxdb_host: 192.168.1.18
influxdb_port_api: 8086
# influxdb for tasseo
influxdb_tasseo_username: collectd
influxdb_tasseo_password: browse
influxdb_tasseo_url: http://{{influxdb_host}}:{{influxdb_port_api}}/db/collectd
# --------------------------------------------------------------------
# tasseo dashboard
# --------------------------------------------------------------------
tasseo_dir: /home/{{deploy_user}}/src/tasseo
tasseo_host: 192.168.1.18
tasseo_port: 5000
# --------------------------------------------------------------------
# visage dashboard
# --------------------------------------------------------------------
visage_dir: /home/{{deploy_user}}/src/visage
visage_host: 192.168.1.18
visage_port: 5001
# --------------------------------------------------------------------
# grafana
# --------------------------------------------------------------------
grafana_previous: 1.6.1
grafana_version: 2.0.2
grafana_url: http://grafanarel.s3.amazonaws.com/builds/grafana-{{grafana_version}}_amd64.deb
grafana_user: kibana
grafana_pwd: banana2013
grafana_domain: 192.168.1.18
grafana_port: 7070
# port is grafana / nginx make proxy to real elasticsearch port
grafana_es: http://{{grafana_domain}}:{{grafana_port}}/es
# port is grafana / nginx make proxy to real influxdb port
grafana_influxdb: http://{{influxdb_host}}:{{grafana_port}}/es

