---
- name: Install Postgresql and related packages if on Ubuntu 12.04
  apt: pkg={{ item }} state=installed
  with_items:
    - postgrey
    - postgresql-9.1
    - postgresql-common
    - postgresql-client
    - postgresql-contrib
    - postgresql-plpython-9.1
    - python-psycopg2
    - libpq-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"
  tags: postgresql

- name: Install Postgresql and related packages if on Ubuntu 14.04
  apt: pkg={{ item }} state=installed
  with_items:
    - postgrey
    - postgresql-9.3
    - postgresql-common
    - postgresql-client
    - postgresql-contrib
    - postgresql-plpython-9.3
    - python-psycopg2
    - libpq-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "trusty"
  tags: postgresql

- name: Set postgres password
  command: sudo -u postgres psql {{ db_admin_username }} -c "ALTER USER postgres with password '{{ db_admin_password }};'"
  tags: postgresql

- name: Add adminpack extension to postgres
  command: 'sudo -u postgres psql {{ db_admin_username }} -c "CREATE EXTENSION IF NOT EXISTS adminpack;"'
  tags: postgresql

