---
- name: Postgresql | install server and related packages if on Ubuntu 12.04
  apt: pkg={{ item }} state=installed
  with_items:
    - postgrey
    - postgresql-9.1
    - postgresql-common
    - postgresql-client
    - postgresql-contrib
    - postgresql-plpython-9.1
    - python-psycopg2
    - libpq-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"
  tags: postgresql

- name: Postgresql | install server and related packages if on Ubuntu 14.04
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-9.3
    - postgresql-common
    - postgresql-client
    - postgresql-contrib
    - postgresql-plpython-9.3
    - python-psycopg2
    - libpq-dev
    # - postgrey
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "trusty"
  tags: postgresql

- name: Postgresql | check directory /var/run/postgresql
  file: path=/var/run/postgresql 
        state=directory
        owner=postgres
        mode=0755
  tags: postgresql

- name: Postgresql | copy SSL certificate
  copy: src=postgresql.crt dest=/etc/pki/tls/certs/postgresql.crt owner=postgres group=postgres mode=0500
  notify:
    - restart postgresql
  tags: postgresql

- name: Postgresql | copy private key
  copy: src=postgresql.key dest=/etc/pki/tls/private/postgresql.key owner=postgres group=postgres mode=0500
  notify:
    - restart postgresql
  tags: postgresql

- name: Postgresql | Copy config files hba to default cluster 9.3/main
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres backup=yes
  notify:
    - restart postgresql
  tags: postgresql

- name: Postgresql | Copy config files master to default cluster 9.3/main
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres backup=yes
  notify:
    - restart postgresql
  tags: postgresql

- name: Postgresql | Start the service
  service: name=postgresql state=started enabled=true
  tags: postgresql

- name: Postgresql | Set admin password
  command: sudo -u postgres psql {{ pg_admin_username }} -c "ALTER USER postgres with password '{{ pg_admin_password }}';"
  tags: postgresql

- name: Postgresql | Add adminpack extension
  command: sudo -u postgres psql {{ pg_admin_username }} -c "CREATE EXTENSION IF NOT EXISTS adminpack;"
  tags: postgresql

- name: Postgresql | Create role {{deploy_user}}
  shell: "sudo -u postgres createuser -d -r {{deploy_user}} || true"
  tags: postgresql

- name: Configure individual collectd plugin
  template: src=collectd/collectd.conf.d/{{item}}.conf.j2 dest=/etc/collectd/collectd.conf.d/
  with_items:
  - posgresql
  tags: postgresql collectd
  notify: restart collectd



