---
- name: Install Redis and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - redis-server
  tags: redis

- name: Redis | Start the service
  service: name=redis-server state=started enabled=true
  tags: redis


