---
- name: Collectd | Install pkg
  apt: pkg={{item}} state=installed
  with_items:
    - collectd
  tags: 
    - collectd

- name: Collectd | Copy main config file
  template: src=collectd/collectd.conf.j2 
            dest=/etc/collectd/collectd.conf
  tags: 
    - collectd
  notify: 
    - restart collectd

- name: Collectd | Configure collection
  template: src=collectd/collection.conf.j2 dest=/etc/collectd/collection.conf
  tags: 
    - collectd
  notify: 
    - restart collectd

- name: Collectd | Configure individual plugin
  template: src=collectd/collectd.conf.d/{{item}}.conf.j2 
            dest=/etc/collectd/collectd.conf.d/{{item}}.conf
  with_items:
    - aggregation
    - ampq
    - curl
    - dbi
    - df
    - disk
    - dns
    - ethstat
    - filters
    - interface
    - md
    - network
    - ntpd
    - rrdtool
    - statd
    - swap
    - thresholds
  tags: 
    - collectd
  notify: 
    - restart collectd

- name: Collectd | Deploy monit config
  template: src=monit.d/collectd.conf.j2  dest=/etc/monit/conf.d/collectd.conf
  notify:
    - reload monit
  tags:
    - collectd
    - monit

- name: Collectd | Configure rsyslog 
  template: src=rsyslog.d/22-collectd.conf.j2 dest=/etc/rsyslog.d/22-collectd.conf
  tags: 
    - collectd
    - rsyslog
  notify: 
    - restart rsyslog
