---
- name: fail2ban | install 
  apt: name="{{ item }}" state=present
  with_items:
    - fail2ban
    - rkhunter
    - lynis
  tags: fail2ban

- name: fail2ban | Config file
  template: src="{{ item.a }}" dest="{{ item.b }}"
  with_items:
    - { a: 'fail2ban.conf.j2', b: '/etc/fail2ban.conf'}
    - { a: 'jail.conf.j2',     b: '/etc/fail2ban/jail.conf'}
  tags: fail2ban
  notify: 
    - restart fail2ban

