---
- name: fail2ban | install 
  apt: name="{{ item }}" state=present
  with_items:
    - fail2ban
    - rkhunter
    - lynis
  tags: fail2ban

- name: fail2ban | Config file
  template: src=fail2ban.conf.j2 dest=/etc/fail2ban/fail2ban.conf
  template: src=jail.conf.j2 dest=/etc/fail2ban/jail.conf
  tags: fail2ban
  notify: 
    - restart fail2ban

