---
- name: Generate locale if needed
  command: locale-gen {{locale}}
  ignore_errors: True
  tags: locale

- name: Set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}  
  tags: locale
