---
### for all servers
- import_tasks: tz.yml
- import_tasks: locale.yml
- import_tasks: deploy.yml
- import_tasks: apt.yml
- import_tasks: ntp.yml
- import_tasks: mosh.yml
- import_tasks: python.yml
### security
- import_tasks: ssh.yml
- import_tasks: ufw.yml
- import_tasks: fail2ban.yml
- import_tasks: logwatch.yml
- import_tasks: security.yml
### admin client
- import_tasks: logrotate.yml
- import_tasks: rsyslog.yml
- import_tasks: collectd.yml
### monit install
- import_tasks: monit.yml
### all hooks for monit
- import_tasks: monit-post.yml
