---
- name: Monit | Install pgk
  apt: name={{item}} state=present
  with_items:
    - libtool
    - autoconf
    - automake
    - flex
    - bison
    - libssl-dev
    - libpam-dev
    - make
    - gcc
    - monit
  tags: 
    - monit

- name: Monit | Create group if not exist
  group: name=monit state=present
  tags: 
    - monit

- name: Monit | check monit conf dir
  file: path=/etc/monit/conf.d group=monit state=directory
  tags:
    - monit

- name: monit | Copy source
  git: repo=https://bitbucket.org/pierreaubert/monit.git
       dest=/home/{{deploy_user}}/src/monit
       version={{monit_version}}
  tags: 
    - monit

- name: monit | Build
  shell: "cd /home/{{deploy_user}}/src/monit && sh ./bootstrap && sh ./configure && make"
  tags: 
    - monit

- name: monit | Stop if running
  service: name=monit state=stopped
  tags: 
    - monit

- name: monit | Overwrite official binary
  command: "cp /home/{{deploy_user}}/src/monit/monit /usr/bin"
  tags: 
    - monit

- name: monit | Start again if not running
  service: name=monit state=started
  tags: 
    - monit

- name: Monit | Deploy main config file
  template: src=monit.conf.j2 dest=/etc/monit/monitrc
  tags: 
    - monit
  notify: 
    - restart monit

- name: Monit | Add {{deploy_user}} in monit group
  user: name={{deploy_user}} groups=monit state=present
  tags: 
    - monit

- name: Monit | Start the service
  service: name=monit state=started enabled=true
  tags: 
    - monit

