---
- name: Monit | Install pgk
  apt: name={{item}} state=installed
  with_items:
   - monit
  tags: monit

- name: Monit | Deploy main config file
  template: src=monit.conf.j2 dest=/etc/monit/monitrc
  tags: monit
  notify: 
    - restart monit

- name: Monit | Create group if not exist
  group: name=monit state=present
  tags: 
    - monit

- name: Monit | Open {{monit_port}} on lan
  ufw: rule=allow src={{fw_subnet}} dest=any port={{monit_port}}
  tags: 
    - monit
    - ufw

- name: Monit | Add {{user_deploy}} in monit group
  user: name={{deploy_user}} groups=monit state=present
  tags: 
    - monit

- name: Monit | Start the service
  service: name=monit state=started enabled=true
  tags: monit

