---
- name: "ntp | Install missing packages"
  apt: name="{{item}}" state=present
  with_items:
    - ntpdate
    - ntp
  tags:
    - ntp

- name: ntp | deploy configuration file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
    - ntp
  notify: 
    - restart ntp

- name: ntp | Start the service
  service: name=ntp state=started enabled=true
  tags: 
    - ntp

