---
- name: Install ntp 
  apt: name={{item}} state=installed
  with_items:
   - ntpdate
   - ntp
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: 
    - restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp

