---
# Installs and configures python
- name: Create a .pip directory 
  command: mkdir -p /home/{{deploy_user}}/.pip
  tags:
    - deploy
    - pip
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"

- name: Change ownership of .pip cache
  command: chown -R {{deploy_user}}:{{deploy_user}} /home/{{deploy_user}}/.pip
  tags:
    - deploy
    - pip
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"

- name: Copy a default pip configuration file
  template: src=pip.conf.j2 dest=/home/{{deploy_user}}/.pip/pip.conf
  tags:
    - deploy
    - pip
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"

- name: Python | Create .pip if it doesn't exist
  command: mkdir -p /root/.pip state=present
  tags: python
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"

- name: Python | Setup Cache for pip
  template: src=pip.conf.j2 dest=/root/.pip/pip.conf
  tags: python
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "precise"

- name: Python | Install pip
  apt: pkg={{item}}
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - virtualenvwrapper
    - supervisor
  tags: python

- name: Python | Install certifi
  apt: pkg={{item}}
  with_items:
    - python-certifi
  when: ansible_distribution_release == "trusty"
  tags: python

- name: Start supervisor
  service: name=supervisor state=started enabled=true
  tags: 
    - python
    - supervisor




