---
- name: Rsyslog | Add ppa
  apt_repository: repo='ppa:adiscon/v8-stable'
  tags: 
    - rsyslog

- name: Rsyslog | Install basic packages
  apt: name={{item}} state=installed
  with_items:
   - rsyslog
  tags: 
    - rsyslog

- name: Rsyslog | Copy main config file
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.conf
  tags: 
    - rsyslog
  notify: 
    - restart rsyslog

- name: Configure rsyslog per channel
  template: src=rsyslog.d/{{item}}.j2 dest=/etc/rsyslog.d/{{item}}
  with_items:
    - 50-default.conf
  tags: 
    - rsyslog
  notify: 
    - restart rsyslog

