---
- name: At | install client
  apt: name={{item}} state=present
  with_items:
   - at
  tags: at
  
- name: Check ownership of /usr/bin/at
  file: path=/usr/bin/at owner=root
  tags:
    - security
