---
- name: Configure ssh file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  tags: ssh
  notify: restart ssh

- name: Start the ssh service
  service: name=ssh state=started enabled=true
  tags: ssh

