---
- name: Configure ssh file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  tags: ssh
  notify: restart ssh

- name: Ssh | Deploy monit config
  template: src=monit.d/openssh-server.conf.j2 dest=/etc/monit/conf.d/openssh-server.conf
  notify:
    - reload monit
  tags:
    - ssh
    - monit

- name: Start the ssh service
  service: name=ssh state=started enabled=true
  tags: ssh

