---
- name: set more secure sysctl values
  sysctl: name={{item.n}} value={{item.v}} sysctl_set=yes state=present reload=yes
  with_items:
    # IP Spoofing protection
    - {n: "net.ipv4.conf.all.rp_filter", v: 1}
    - {n: "net.ipv4.conf.default.rp_filter", v: 1}
    # Ignore ICMP broadcast requests
    - {n: "net.ipv4.icmp_echo_ignore_broadcasts", v: 1}
    # Disable source packet routing
    - {n: "net.ipv4.conf.all.accept_source_route", v: 0}
    - {n: "net.ipv6.conf.all.accept_source_route", v: 0 }
    - {n: "net.ipv4.conf.default.accept_source_route", v: 0}
    - {n: "net.ipv6.conf.default.accept_source_route", v: 0}
    # Ignore send redirects
    - {n: "net.ipv4.conf.all.send_redirects", v: 0}
    - {n: "net.ipv4.conf.default.send_redirects", v: 0}
    # Block SYN attacks
    - {n: "net.ipv4.tcp_syncookies", v: 1}
    - {n: "net.ipv4.tcp_max_syn_backlog", v: 2048}
    - {n: "net.ipv4.tcp_synack_retries", v: 2}
    - {n: "net.ipv4.tcp_syn_retries", v: 5}
    # Log Martians
    - {n: "net.ipv4.conf.all.log_martians", v: 1}
    - {n: "net.ipv4.icmp_ignore_bogus_error_responses", v: 1}
    # Ignore ICMP redirects
    - {n: "net.ipv4.conf.all.accept_redirects", v: 0}
    - {n: "net.ipv6.conf.all.accept_redirects", v: 0}
    - {n: "net.ipv4.conf.default.accept_redirects", v: 0 }
    - {n: "net.ipv6.conf.default.accept_redirects", v: 0}
    # Ignore Directed pings
    - {n: "net.ipv4.icmp_echo_ignore_all", v: 1}
  tags:
    - sysctl
