---
# Installs and configures ufw

# ufw includes sensible icmp defaults
- name: firewall | Install ufw
  apt: pkg=ufw state=present
  tags:
    - ufw

- name: firewall | Ratelimit ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  tags:
    - ufw
  become: true

- name: firewall | Allow openssh
  ufw:
    rule: allow
  tags:
    - ufw
  become: true

- name: firewall | Delete OpenSSH rule
  ufw:
    rule: allow
    delete: yes
  tags:
    - ufw
  become: true

- name: firewall | Allow mosh
  ufw: 
    rule: allow
    port: '60000:61000'
    proto: udp
  tags:
    - ufw
  become: true

- name: firewall | Allow roon (tcp)
  ufw: 
    rule: allow
    port: '9100:9200'
    proto: tcp
    src: 192.168.1.0/24
  tags:
    - ufw
    - roon
  become: true

- name: firewall | Allow roon (udp)
  ufw: 
    rule: allow
    port: 9003
    proto: udp
    src: 192.168.1.0/24
  tags:
    - ufw
    - roon
  become: true

- name: firewall | Check status of ufw
  command: ufw status
  register: ufw_status
  changed_when: False  # never report as "changed"
  tags:
    - ufw
  become: true

- name: firewall | Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False  # never report as "changed"
  tags:
    - ufw
  become: true

- name: firewall | Disable logging (workaround for known bug in Debian 7)
  command: ufw logging off
  when: "ansible_lsb['codename'] == 'wheezy' and 'LOGLEVEL=off' not in ufw_config.stdout"
  tags:
    - ufw
  become: true

- name: firewall | Enable ufw
  ufw: 
    state: enabled
  tags:
    - ufw
  become: true

- name: firewall | Copy ufw conf for rsyslog
  template: src=rsyslog.d/20-ufw.conf.j2 
            dest=/etc/rsyslog.d/20-ufw.conf
  tags:
    - ufw
    - rsyslog

