---
# ----------------------------------------------------------------------
# gateway and main interface
# ----------------------------------------------------------------------
gateway_host: 192.168.1.1
interface: enp9s0
# ----------------------------------------------------------------------
# locale and timezone
# ----------------------------------------------------------------------
locale: fr_FR.UTF-8
timezone: Europe/Paris
# ----------------------------------------------------------------------
# monit
# ----------------------------------------------------------------------
collectd_server: 192.168.1.18
collectd_port: 25826
# ----------------------------------------------------------------------
# monit
# ----------------------------------------------------------------------
monit_host: 192.168.1.18
monit_port: 2812
monit_username: '{{deploy_user}}'
monit_password: 'monit.2014'
monit_version: feature/slack
# ----------------------------------------------------------------------
# network
# ----------------------------------------------------------------------
fw_subnet: 192.168.1.0/24
# ----------------------------------------------------------------------
# slack webhook
# ----------------------------------------------------------------------
slack_webhook: https://7pi.slack.com/services/hooks/incoming-webhook?token=7QnKJAmD6so5dpZSBi1TAA4S